language: php
php:
- 7.4
before_install:
- printenv
- openssl aes-256-cbc -K $encrypted_f217180e22ee_key -iv $encrypted_f217180e22ee_iv
  -in id_rsa.enc -out id_rsa -d
addons:
  ssh_known_hosts:
  - 210.116.80.33:22000
install:
- echo "Installing lftp"
- sudo apt-get install lftp
script:
- printenv
- echo "Deploying to SFTP server"
- echo "Setting up ssh-agent"
- eval "$(ssh-agent -s)"
- echo "Adding ssh key to ssh-agent"
- chmod 600 id_rsa
- ssh-add id_rsa
- echo "Syncing files to SFTP server"
- lftp -c "set sftp:auto-confirm yes; open sftp://$FTP_USER:$FTP_PASS@$FTP_HOST:$FTP_PORT/home/mingu;
  mirror -R --ignore-time ."
deploy:
  on:
    branch: dev
