language: php
php:
  - 7.4
before_script:
  - phpenv config-rm xdebug.ini
before_deploy:
  - composer install --no-dev --optimize-autoloader
deploy:
  provider: sftp
  host: $FTP_HOST
  user: $FTP_USER
  password: $FTP_PASS
  port: $FTP_PORT
  path: /home/mingu
  on:
    branch: dev
