language: php

php:
  - 7.4

before_install:
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in deploy_rsa.enc -out deploy_rsa -d

install:
  - echo "Installing lftp"
  - sudo apt-get install lftp

script:
  - echo "Deploying to SFTP server"
  - echo "Setting up ssh-agent"
  - eval "$(ssh-agent -s)"
  - echo "Adding ssh key to ssh-agent"
  - chmod 600 deploy_rsa
  - ssh-add deploy_rsa
  - echo "Syncing files to SFTP server"
  - lftp -c "set sftp:auto-confirm yes; open sftp://$SFTP_USER:$SFTP_PASS@$210.116.80.33:22000/home/mingu; mirror -R --ignore-time ."

deploy:
  provider: script
  script: bash script/deploy.sh
  on:
    branch: dev
