language: php
php:
  - 7.4
before_deploy:
  - composer install --no-dev --optimize-autoloader
deploy:
  provider: sftp
  host: 210.116.80.33
  port: 22000
  user: $FTP_USER
  password: $FTP_PASSWORD
  path: '/home/mingu'
  on:
    branch: dev
