<?
//////////////////////////////////////////////////////////////
//
// 	Date 		: 2004/03/02
// 	Last Update : 2004/03/02
// 	Author 		: Park, ChanHo
// 	History 	: 2004.03.02 by Park ChanHo 
// 	File Name 	: global_init.inc
// 	Description : 관리자 global 변수
// 	Version 	: 1.0
//
//////////////////////////////////////////////////////////////
$g_site_title = ":::::유니시티기업 홈 사이트 관리자페이지 입니다.:::::";
$g_site_name = "유니시티 기업 홈";
$g_site_url = "http://www.makelifebetter.co.kr";
?>