on:
  push:
    branches:    
      - dev
      
name: Deploy
jobs:
  deploy_job:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
      
    - name: 📂 Sync files
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        server: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        forceUpload: true                          
        local_path: './*'
        remoteDir: '/home/mingu'
        port: ${{ secrets.PORT }}
        sftp_only: true
