on:
  push:
    branches:    
      - dev
      
name: Build and Publish Averment
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: ${{ secrets.HOST }}
        FTP_USERNAME: ${{ secrets.USERNAME }}
        FTP_PASSWORD: ${{ secrets.PASSWORD }}
        LOCAL_DIR: /home/mingu
        METHOD: sftp
        PORT: ${{ secrets.PORT }}
